version: 2

updates:
  - package-ecosystem: uv
    directory: /
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "ci(gha): "
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    commit-message:
      prefix: "build(docker): "
    schedule:
      interval: monthly
